include:
  # Settings reset - flash this first to clear stored Bluetooth name and settings
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset_nice_nano

  - board: nice_nano
    shield: corne
    snippet: studio-rpc-usb-uart